version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    volumes:
      - ./postgres/pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "shopify_monitor", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
  flyway:
    image: flyway/flyway:8.5.13
    container_name: flyway
    volumes:
      - ./flyway/sql_versions/:/flyway/sql
      - ./flyway/flyway.config:/flyway/conf/flyway.config
    entrypoint: [ "bash" ]
    command: >
      -c "/flyway/flyway -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}